version: '3.8'
services:
  jolt-template:
    build:
      context: ./docker/java/Dockerfile
    container_name: jolt-app
    env_file:
      - .env
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./src:/workspace/src
      - ./certs:/app/tmp/tomcat/certs:ro
    depends_on:
      postgres:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./src/main/java
          target: /workspace/src/main/java
          ignore:
            - target/
        - action: rebuild
          path: ./pom.xml
          target: /workspace/pom.xml

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: jolt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: jolt_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d jolt_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
    driver: local
